export const SUBSCRIPTION_TYPE = {
  MONTHLY: 'monthly',
  YEARLY: 'yearly',
  FREE: 'free'
};

export const SUBSCRIPTION_STATUS = {
  CREATED: 'created',
  ACTIVE: 'active',
  DEACTIVATED: 'deactivated'
};

export const NEW_SUBSCRIPTION_CHANNEL = 'NEW_SUBSCRIPTION_CHANNEL';
export const SUBSCRIPTION_STATS_JOB = 'SUBSCRIPTION_STATS_JOB';
export const COUNT_SUBSCRIPTION_STATS_CHANNEL = 'COUNT_SUBSCRIPTION_STATS_CHANNEL';
